
export const ADD_USER = 'add_user'
export const ADD_USER_FAILED = 'add_user_failed'
export const SIGNIN = 'signin'
export const SIGNOUT = 'signout'
export const SIGNIN_FAILED = 'sigin_failed'
export const ADD_CONTENT = 'add_content'
export const ADD_CONTENT_FAILED = 'add_content_failed'
export const EDIT_CONTENT = 'edit_content'
export const EDIT_CONTENT_FAILED = 'edit_content_failed'
export const DELETE_CONTENT = 'delete_content'
export const DELETE_CONTENT_FAILED = 'delete_content_failed'
export const LOAD_CONTENTS = 'load_contents'
export const LOAD_CONTENTS_FAILED = 'load_contents_failed'
export const SAVE_USER = "SAVE_USER";